apiVersion: v1
kind: Pod
metadata:
  name: podu
  labels:
    app: podu
spec:
  containers:
  - name: kubeki-app
    image: kdocku/fareye_kube:latest
    ports:
    - containerPort: 3000
  imagePullSecrets:
    - name: my-registry-secret


# apiVersion: v1 #kubernetes api version used to create this object
# kind: Pod #the type of object being created
# metadata: #data that helps uniqiuely idenfiying the object, including it name and label
#   name: podu # the name of the pod
#   labels: #key-value pairs used to orgranize and select group of objects
#     app: podu
# specs: #Describe the desired state of pod
#   containers: #An array of containers that should be run in this pod
#     - name: kubeki-app # name of the container
#   image: kdocku/fareye_kube:latest # container image to run
#   ports: #Ports to expose on the container
#     - containerPort: 3000
# # this is required for private docker image with docker login else we can omitt this step
# imagePullSecrets: 
#   - name: my-registry-secret


